### ISSUE TITLE
rules_haskell failing on Bazel CI

### ISSUE THREAD

**Issue by meteorcloudy** [tweag/rules_haskell#1137]
https://buildkite.com/bazel/rules-haskell-haskell/builds/155

```
(00:23:20) ERROR: An error occurred during the fetch of repository 'proto-lens-protoc':
   Platform is not supported (see 'fail_not_supported')
(00:23:20) ERROR: /workdir/tests/BUILD.bazel:40:1: //tests:protobuf-toolchain-impl depends on @proto-lens-protoc//:bin/proto-lens-protoc in repository @proto-lens-protoc which failed to fetch. no such package '@proto-lens-protoc//': Platform is not supported (see 'fail_not_supported')
```

**Comment by Profpatsch** [comment]
Why is `proto_lens_protoc` not supported on Linux? Did something change in bazel’s protobuf rules?

**Comment by aherrmann** [comment]
@meteorcloudy The target that fails to build (`//tests:protobuf-toolchain-impl`) is marked with `tags = ["requires_hackage", "requires_proto"],` and should therefore be excluded by `--build_tag_filters=-requires_hackage,...` which the buildkite log shows to be set. It seems that Bazel ignores the `--build_tag_filters` flag in this case. Could it be that Bazel ignores that flag on toolchains?

@Profpatsch It's provisioned by `rules_nixpkgs`.

**Comment by Profpatsch** [comment]
There’s also proto-lens 0.6 now, maybe related? 
https://github.com/tweag/rules_haskell/issues/1111#issuecomment-547631898

**Comment by meteorcloudy** [comment]
I'm not sure why the target was not excluded. But I did a bisect, looks like the culprit is 56c37b4f4099b83cab5fda2b77ddc9103d5af885

**Comment by aherrmann** [comment]
I see, since those targets don't have that tag themselves they are not excluded and since they depend on the proto toolchain Bazel tries to build it anyway.

https://github.com/tweag/rules_haskell/pull/1138 should fix this by no longer requiring nixpkgs to provision the proto toolchain. We could also just add the tag to those tests to exclude them on Bazel CI, but it seems better to test more things rather than less.
