### ISSUE TITLE
`extra_srcs` doesn't seem to work with generated files

### ISSUE THREAD

**Issue by joneshf** [tweag/rules_haskell#1296]
**Describe the bug**

It appears that when we have a file in `extra_srcs` that is generated by a rule like `write_file`, the file is not correctly tracked as a dependency. This doesn't seem to fail if either the file is a source file (not generated) or if we have a generated file in `srcs`. That seems to indicate that the issue is with `extra_srcs`.

I'm not entirely sure what's going wrong.

**To Reproduce**

I threw together a [repo](https://github.com/joneshf/rules_haskell_extra_srcs) that reproduces the issue.

* If `extra_srcs` is used, it looks like it has to be used with [real source files](https://github.com/joneshf/rules_haskell_extra_srcs/commit/4269f33d13bcab1f02e4a8d6eb6ab36b817399a8).
* If `srcs` is used, it looks like it can be used with [generated files](https://github.com/joneshf/rules_haskell_extra_srcs/commit/bd4075cba46459a3ae0a3d0fcbdc40f2cbdd7baf).

**Expected behavior**

It seems like `extra_srcs` should be able to depend on generated files. 

**Environment**
- OS name + version:

    ```console
    $ uname --all
    Linux arch-laptop-novo 5.5.4-arch1-1 #1 SMP PREEMPT Sat, 15 Feb 2020 00:36:29 +0000 x86_64 GNU/Linux
    ```

- Bazel version:

    ```console
    $ bazel version
    Build label: 2.2.0- (@non-git)
    Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
    Build time: Fri Mar 13 15:11:54 2020 (1584112314)
    Build timestamp: 1584112314
    Build timestamp as int: 1584112314
    ```

- Version of the rules: https://github.com/tweag/rules_haskell/commit/b1cea20863b62053619e2902746657f3c4c9ac9b

**Additional context**

**Comment by smelc** [comment]
Issue is reproducible with bazel `2.0.0`. Btw thanks for the very detailed issue!

**Comment by smelc** [comment]
The generated file seems correctly tracked. In `private/haskell/haskell_impl.bzl`, I witness that `hs_info` seems correct:

```
DEBUG: haskell_impl.bzl:485:5: hs_info.source_files: depset([<source file Foo.hs>])
DEBUG: haskell_impl.bzl:486:5: hs_info.extra_source_files: depset([<generated file README.md>, <generated file compile-package_env-foo>, <generated file optp_args_foo>])
```

**Comment by aherrmann** [comment]
A generated file will have a different position in the sandbox than a source file, if you adapt your debug output to print `file.path` then you should be able to see that difference. 

We have an [example in the `rules_haskell` test suite](https://github.com/tweag/rules_haskell/blob/2c4c3567e1bef3528bb378dbfa98dd74546160e5/tests/binary-with-tool/BUILD.bazel) that is similar, in that it refers to a generated binary during compile time. Since the path needs to be known within a pragma we use CPP to insert a generated value.

In the use-case presented in this issue it should be possible to avoid CPP with a generated source file capturing the path within the sandbox. Something along the lines of
```
genrule(
    name = "locations",
    outs = ["Locations.hs"],
    srcs = ["README.md"],
    cmd = """\
cat >$(OUTS) <<EOF
module Locations where

readme :: FilePath
readme = "$(execpath README.md)"
EOF
""",
)
```

**Comment by joneshf** [comment]
I was afraid something like that might be the case. I guess there's not really a way to map the file path in a Haskell source file to the generated file location? Something like runfiles, but at compile time.

For posterity, is the reason it works for `srcs` that the path is munged to find the module? E.g. `"Foo/Bar/Baz.hs"` and `"bazel-out/k8-fastbuild/bin/Foo/Bar/Baz.hs"` are both munged to `"Foo.Bar.Baz"`?

**Comment by aherrmann** [comment]
> I was afraid something like that might be the case. I guess there's not really a way to map the file path in a Haskell source file to the generated file location? Something like runfiles, but at compile time.

Since this happens at build time, it's typically done using tools like [`execpath`](https://docs.bazel.build/versions/master/be/make-variables.html#predefined_label_variables), as shown in the `genrule` snippet I posted above.

The mapping prefix `bazel-out/k8-fastbuild/bin` is available in [`ctx.bin_dir`](https://docs.bazel.build/versions/master/skylark/lib/ctx.html#bin_dir). So, knowing that, you can predict the path of a generated file. In principle, one could write a library that does this and call it in template Haskell. Whether the complexity is worth it probably depends on the use-case.

> For posterity, is the reason it works for `srcs` that the path is munged to find the module? E.g. `"Foo/Bar/Baz.hs"` and `"bazel-out/k8-fastbuild/bin/Foo/Bar/Baz.hs"` are both munged to `"Foo.Bar.Baz"`?

The reason it works for `srcs` is that those are all passed to GHC directly on the commandline. So, GHC never has to look for those files, it knows where they are right away.

**Comment by joneshf** [comment]
That all makes sense. It sounds like there's nothing really to do here. Thanks for the explanations!

For completeness, I ended up using `actions.expand_template` and dropping `file-embed`.
