### ISSUE TITLE
Support Remote Execution

### ISSUE THREAD

**Issue by hanshoglund** [tweag/rules_haskell#1318]
**Describe the solution you'd like**
`rules_haskell` should be compatible with [Remote Execution](https://docs.bazel.build/versions/master/remote-execution.html) over the [RBE protocol](https://github.com/bazelbuild/remote-apis).

This entails:

- Making the rule set pure (related: #1265, in a way #1320)
- Setting up the RE environment (related: #940)
- Testing and benchmarking
- Setting up reproducible execution environments. Two possible strategies:
  - Use external declaratice spec (Nix, Dockerfiles)
  - Use Bazel itself to build images
  - Use a minimal host env and make everything explicit

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by mboes** [comment]
@hanshoglund could you adjust the description of this ticket? Supporting remote execution without Nixpkgs is straightforward (but much harder with Nixpkgs). The missing pieces are given in https://github.com/tweag/rules_haskell/issues/940#issuecomment-501769962. The first bullet point listed there corresponds to the newly created #1320. In fact, it's unclear what else would need to be done for remote execution once that ticket is resolved, except to make sure that a host toolchain repository rule is marked as `remotable`, that the user is passing `--experimental_repo_remote_exec` to Bazel, and document the necessary configuration in our user guide.

The `remotable` stuff is necessary, because even with a host toolchain, we still need some amount of autoconfiguration, in particular to run `pkgdb_to_bzl.py`, which discovers the ghc-pkg db content and creates a `.bzl` file reflecting that.

#1265 is a not a blocker, and that issue is not about rule set purity. It's the whole point of repository rules to be "impure": to inject dependencies on the host environment or downloadable resources. Different spawn strategies require different boundaries with the host environment, but even after resolving #1265 the bindist repository rule will create a toolchain that still has dependencies on the host environment (and is therefore "impure").

**Comment by mboes** [comment]
We should probably close #940, since after that it would become a duplicate to this issue.

**Comment by hanshoglund** [comment]
All right. I opened a new ticket reflecting the separate use cases:

1. RE where GHC is provided in the RE environment (e.g. Docker). Let's track this in #1321 (basically #1320 plus testing and providing the Docker image).

2. RE compatible with Nixpkgs/non-standard GHC. Let's track in #1322

Closing this.
