### ISSUE TITLE
Support multiple source directories in the same package

### ISSUE THREAD

**Issue by iphydf** [tweag/rules_haskell#135]
WORKSPACE:
```python
new_http_archive(
    name = "haskell_bifunctors",
    build_file = "third_party/haskell/BUILD.bifunctors",
    sha256 = "332bb2ea19e77dac55282daff8046d89f69514ced5b987779d887e53b5d7cb11",
    strip_prefix = "bifunctors-5.5.2",
    urls = ["https://hackage.haskell.org/package/bifunctors-5.5.2/bifunctors-5.5.2.tar.gz"],
)
```

BUILD.:
```python
load("@io_tweag_rules_haskell//haskell:haskell.bzl", "haskell_library")

haskell_library(
    name = "bifunctors",
    srcs = glob(["src/**/*.hs*"]),
    prebuilt_dependencies = [
        "base",
        "containers",
        "template-haskell",
    ],
    src_strip_prefix = "src",
    visibility = ["//visibility:public"],
)
```

Error:
```
external/haskell_bifunctors/src/Data/Bifunctor/TH/Internal.hs:33:1: error:
    Failed to load interface for `Data.Bifoldable'
    Perhaps you meant Data.Foldable (from base-4.9.0.0)
    Use -v to see a list of the files searched for.
```

See https://hackage.haskell.org/package/bifunctors-5.5.2/bifunctors.cabal, where they conditionally add additional hs-source-dirs. I'd like to unconditionally add them, since I know my ghc version, but there is only one `src_strip_prefix`.

**Comment by mrkkrp** [comment]
I understand the issue, but cannot reproduce it. According to the version of `base` you're using GHC 8.0.2 I guess?

For me it fails in the following way:

```
external/haskell_bifunctors/src/Data/Bifunctor/TH/Internal.hs:27:1: error:
    Could not find module `Language.Haskell.TH.Datatype'
    Perhaps you meant
      Language.Haskell.TH.Quote (from template-haskell-2.12.0.0)
      Language.Haskell.TH.Lib.Map
      Language.Haskell.TH.Ppr (from template-haskell-2.12.0.0)
    Use -v to see a list of the files searched for.
   |
27 | import           Language.Haskell.TH.Datatype
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

external/haskell_bifunctors/src/Data/Bifunctor/TH/Internal.hs:38:1: error:
    Could not find module `Paths_bifunctors'
    Use -v to see a list of the files searched for.
   |
38 | import           Paths_bifunctors (version)
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

1. The first error message is because we need to build `th-abstraction` first and specify it in `deps`.
2. The second error message is because we don't generate yet `Paths_*` files. Probably we should add that though.

**Comment by iphydf** [comment]
Right, 8.0.1 I think. If you use 8.2.2 you won't see the error. The source dir is called "old-src" because it contains modules that weren't present in older base libraries.

**Comment by mboes** [comment]
This in fact was already an issue when building aeson (see #103). I'm loath to support anything more than `strip_src_prefix`, because a) there are workarounds and b) supporting more would push us further into unidiomatic Bazel.

In Bazel, you're meant to have BUILD files essentially per directory. We don't need to be as monolithic as Cabal packages are. In fact granular, local BUILD files is very much the encouraged style. If a Cabal package feels the need to put source in multiple source repositories, then it's likely that these directories are logically distinct. Either way, it works fine to simply define two `haskell_library` targets with one depending on the other. That's what we did for aeson (split up into 3 `haskell_library` targets [here](https://github.com/mboes/bazel-protolude/blob/aeson/WORKSPACE#L305-L357).

**Comment by iphydf** [comment]
Ok, I can probably work with that.
