### ISSUE TITLE
how mandatory is rules_haskell_toolchains / define two ghc.

### ISSUE THREAD

**Issue by teto** [tweag/rules_haskell#1409]
Not a bug, just (2) questions relative to this pice of code:

1/ do I need to call `rules_haskell_toolchains` if I have registered only one ghc via `haskell_register_ghc_nixpkgs` ?
2/ I am trying to experiment with static binaries. I would like to define two toolchains. I tried naming the static one as  `version = "8.8.3static"` but this was not considered a valid version by rules_haskell_toolchains. This is more an hypotehtical question since it may not make sense to have these 2 toolchains defined.
```
    haskell_register_ghc_nixpkgs(
        repositories = {"nixpkgs": "@buildlib//nix:default.nix"},
        attribute_path = "staticHaskell.ghc",
        version = "8.8.3",
        nix_file_deps = nixpkgs_deps,
        compiler_flags_select = {
            "@buildlib//:pedantic": default_flags + pedantic_compiler_flags,
            "@buildlib//:non_pedantic": default_flags,
            "//conditions:default": default_flags + pedantic_compiler_flags,
        },
        static_runtime = True,
        fully_static_link = True,
        **kwargs
    )
    # haskell_register_ghc_nixpkgs(
    #     repositories = {"nixpkgs": "@buildlib//nix:default.nix"},
    #     attribute_path = "haskell.compiler.ghc883",
    #     version = "8.8.3",
    #     nix_file_deps = nixpkgs_deps,
    #     compiler_flags_select = {
    #         "@buildlib//:pedantic": default_flags + pedantic_compiler_flags,
    #         "@buildlib//:non_pedantic": default_flags,
    #         "//conditions:default": default_flags + pedantic_compiler_flags,
    #     },
    #     **kwargs
    # )
    rules_haskell_toolchains(version = "8.6.5")
```

**Comment by aherrmann** [comment]
> 1/ do I need to call `rules_haskell_toolchains` if I have registered only one ghc via `haskell_register_ghc_nixpkgs` ?

No, if you only intend to use a Nix provided GHC toolchain, then it is enough to call `haskell_register_ghc_nixpkgs` alone. `rules_haskell_toolchains` on the other hand is used to download a GHC binary distribution from https://downloads.haskell.org. The `rules_haskell` repository happens to call both because we want to test both kinds of toolchains on CI.

> 2/ I am trying to experiment with static binaries. I tried naming the static one as `version = "8.8.3static"` but this was not considered a valid version by rules_haskell_toolchains.

This is indeed not valid, the `version` attribute must match the actual version of GHC. The `version` attribute is also not used to select between GHC toolchains. The registered GHC toolchain is a regular [Bazel toolchain](https://docs.bazel.build/versions/master/toolchains.html) and Bazel uses platform constraints to select between multiple registered toolchains as described [here](https://docs.bazel.build/versions/master/toolchains.html#toolchain-resolution). However, assigning platform constraints to the GHC toolchain is [not exposed to the user](https://github.com/tweag/rules_haskell/blob/5294e36d41933cb6d30eaa2335d4be6710eb2f57/haskell/nixpkgs.bzl#L139-L145).

> This is more an hypotehtical question since it may not make sense to have these 2 toolchains defined.

A GHC toolchain configured for fully static linking will still produce dynamically linked binaries if `-optl-static` is not passed (or `fully_static_link` is not enabled as of #1410). So, it is still possible to create dynamically linked binaries with such a toolchain and unclear whether a second toolchain would really be required.

**Comment by teto** [comment]
thanks for the excellent explanation. Thanks for taking the time to incorporate links etc.
