### ISSUE TITLE
Invalid symbolic link from ghcide/bench/example/HLS

### ISSUE THREAD

**Issue by teto** [tweag/rules_haskell#1503]
**Describe the bug**
I've tried to bump our hasskell-language-server version to the recently release 1.0.0 but it fails because the tarball contains symlinks ?

**To Reproduce**
I am pinning a snapshot version of https://github.com/haskell/haskell-language-server/blob/master/stack-8.8.4.yaml
which gives:
```
bazel run @hls-unpinned//:pin-backup via
Starting local Bazel server and connecting to it...
INFO: Repository hls-unpinned instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule _stack_snapshot_unpinned defined at:
  /home/teto/.cache/bazel/_bazel_teto/ddd5071618e4f7743592d457ad28382d/external/rules_haskell/haskell/cabal.bzl:1908:43: in <toplevel>
ERROR: An error occurred during the fetch of repository 'hls-unpinned':
   Traceback (most recent call last):
	File "/home/teto/.cache/bazel/_bazel_teto/ddd5071618e4f7743592d457ad28382d/external/rules_haskell/haskell/cabal.bzl", line 1661
		_resolve_packages(<6 more arguments>)
	File "/home/teto/.cache/bazel/_bazel_teto/ddd5071618e4f7743592d457ad28382d/external/rules_haskell/haskell/cabal.bzl", line 1155, in _resolve_packages
		_execute_or_fail_loudly(<2 more arguments>)
	File "/home/teto/.cache/bazel/_bazel_teto/ddd5071618e4f7743592d457ad28382d/external/rules_haskell/haskell/private/workspace_utils.bzl", line 18, in _execute_or_fail_loudly
		fail(<1 more arguments>)
Command failed: /home/teto/.cache/bazel/_bazel_teto/ddd5071618e4f7743592d457ad28382d/external/rules_haskell_stack/stack ls dependencies json --global-hints --external
Cloning 4cd1cf934638881e52b3eba9f70157a4b799c0e9 from https://github.com/haskell/haskell-language-server.git
Unsupported tarball from /tmp/with-repo-archive24666/foo.tar: Invalid symbolic link from ghcide/bench/example/HLS to ../../.., tried parsing ghcide/bench/example/../../..: no non-empty components
ERROR: Traceback (most recent call last):
	File "/home/teto/.cache/bazel/_bazel_teto/ddd5071618e4f7743592d457ad28382d/external/rules_haskell/haskell/cabal.bzl", line 1661
		_resolve_packages(<6 more arguments>)
	File "/home/teto/.cache/bazel/_bazel_teto/ddd5071618e4f7743592d457ad28382d/external/rules_haskell/haskell/cabal.bzl", line 1155, in _resolve_packages
		_execute_or_fail_loudly(<2 more arguments>)
	File "/home/teto/.cache/bazel/_bazel_teto/ddd5071618e4f7743592d457ad28382d/external/rules_haskell/haskell/private/workspace_utils.bzl", line 18, in _execute_or_fail_loudly
		fail(<1 more arguments>)
Command failed: /home/teto/.cache/bazel/_bazel_teto/ddd5071618e4f7743592d457ad28382d/external/rules_haskell_stack/stack ls dependencies json --global-hints --external
Cloning 4cd1cf934638881e52b3eba9f70157a4b799c0e9 from https://github.com/haskell/haskell-language-server.git
Unsupported tarball from /tmp/with-repo-archive24666/foo.tar: Invalid symbolic link from ghcide/bench/example/HLS to ../../.., tried parsing ghcide/bench/example/../../..: no non-empty components
```

**Expected behavior**

**Environment**
 - OS name + version: nixos
 - Bazel version: 3.3.1
 - Version of the rules: 1 or 2 commits away from master

**Comment by aherrmann** [comment]
@teto Thanks for reporting! This looks like an issue in `stack` itself. It's the command `stack ls dependencies json --global-hints --external` that fails. I've tried to construct a reproduction with stack alone based on hls's `stack.yaml`, but all it does is hang and eat up memory.

I think it would be good to try and reproduce this issue outside rules_haskell with stack alone, to isolate where the issue lies. The following commands should provide information about which stack version rules_haskell uses and which inputs it provides:
```
# The stack version rules_haskell uses
$ $(bazel info output_base)/external/rules_haskell_stack/stack --version
# The stack.yaml that rules_haskell generates
$ cat $(bazel info output_base)/external/stackage-unpinned/stack.yaml
# The root Cabal file that rules_haskell generates
$ cat $(bazel info output_base)/external/stackage-unpinned/rules-haskell-stack-resolve/rules-haskell-stack-resolve.cabal
```
Finally, the custom stack snapshot that you pass to the `local_snapshot` attribute.

Can you reproduce the issue if you invoke the same `stack` version on a standalone repository that replicates the inputs from above? I.e. a directory tree that looks like this
```
./your-snapshot.yaml  # (adjust the name as appropriate)
./stack.yaml
./rules-haskell-stack-resolve/rules-haskell-stack-resolve.cabal
```
And then run `stack ls dependencies json --global-hints --external`

Also, I don't recognize `@hls-unpinned//:pin-backup` is that any different from `@hls-unpinned//:pin`?

As for a workaround. You could clone the hls repository, remove the symlink, and point your custom stack snapshot to your fork.

**Comment by teto** [comment]
Thanks for the detailed instructions.
probably hls authors will realize the stack issue once they push 1.0 to hackage, will wait for that before investiaging futher

**Comment by aherrmann** [comment]
>  probably hls authors will realize the stack issue once they push 1.0 to hackage

It's possible that the issue will not manifest at that point, at least not in this way. When pushing to Hackage one typically operates on the sdists generated by Cabal, rather than the whole git repository. I'm not sure how Cabal handles cyclic symlinks when generating sdists. It may break at that stage, or go unnoticed. I think it would be worth to raise an issue at hls, if only to save them a bit of time on debugging this issue on their end.

**Comment by Xophmeister** [comment]
@teto Were you able to resolve this issue, or pass it upstream to hls?

**Comment by teto** [comment]
Yes, I use nix instead to handle deps. Thanks !
