### ISSUE TITLE
export hs-boot files to repl

### ISSUE THREAD

**Issue by teto** [tweag/rules_haskell#1532]
**Is your feature request related to a problem? Please describe.**
When running haskell-language-server, it chokes on `SOURCE` imports
`import {-# SOURCE #-}           My.Module ()     ■ Could not find module`

Turns out this is supported in hls and if I add the `*.hs-boot` files to the flags loaded by the hie.yaml file it works fine (I am not a 100% sure yet but in the 2 cases I added the flags manually, the error went away).

**Describe the solution you'd like**
I would like `bazel build "//hie_bios"   --output_groups=hie_bios   --experimental_show_artifacts ` to output the hs-boot files ?

**Describe alternatives you've considered**
I tried to hack my way around in `haskell/repl.bzl` where the sources are listed, seems like .hs-boot files end up in extra_haskell_sources (cf  `haskell/private/actions/compile.bzl`) but then retreieving the info required to have one more level of indirection so I wanted to confirm first what approach to adopt.

**Comment by aherrmann** [comment]
It looks like the issue is that boot files are not tracked in the `HaskellInfo` provider's `source_files` attribute, but instead in the `boot_files` attribute. Provider is constructed [here](https://github.com/tweag/rules_haskell/blob/1b0619438085c5012fb885528c6ea819891de561/haskell/private/haskell_impl.bzl#L239-L240) and the boot files are tracked [here](https://github.com/tweag/rules_haskell/blob/1b0619438085c5012fb885528c6ea819891de561/haskell/private/actions/compile.bzl#L223-L224). I haven't dug further but I suspect this separation is done for good reason. Perhaps we should have a dedicated `boot_files` attribute in `HaskellInfo` instead of mixing boot files into `extra_source_files`. `haskell_repl` could then make sure to include boot files.
