### ISSUE TITLE
Start script is returning 500 error

### ISSUE THREAD

**Issue by AlistairB** [tweag/rules_haskell#1547]
**Describe the bug**
https://haskell.build/start is returning 500 error with no response body.

**To Reproduce**
`curl -v https://haskell.build/start`

**Expected behavior**
Some shell script to be returned.

**Environment**
 - OS name + version: Ubuntu 20.10
 - Bazel version: N/A
 - Version of the rules: N/A

**Comment by aherrmann** [comment]
@AlistairB Thanks for reporting this. Unfortunately, I cannot reproduce the issue, `curl -v https://haskell.build/start` works for me. Can you retry? Perhaps this was a transient error. Though, I don't see any past incidents listed on [netlify status](https://www.netlifystatus.com/).

**Comment by AlistairB** [comment]
Hmm interesting. It continues not to work, although https://haskell.build loads fine.

![image](https://user-images.githubusercontent.com/437253/116976515-9cf97280-ad04-11eb-805a-8f570e3891a9.png)

Happy to close if you think it is an issue on my end somehow.

**Comment by aherrmann** [comment]
> Happy to close if you think it is an issue on my end somehow.

Hard to say where the issue lies. But, I'm afraid there isn't much we can do about it. We've tried different locations and it worked fine in those cases.

Fortunately, the `start` script is also available [directly on GitHub](https://github.com/tweag/rules_haskell/blob/master/start). You can just download it from there and run it in your shell.
