### ISSUE TITLE
hspec-discover in the REPL

### ISSUE THREAD

**Issue by aveltras** [tweag/rules_haskell#1581]
Hi,

I'm wondering if it's possible to have the repl targets use `hspec-discover` like other types of target can using a combination of `tools` and `compiler_flags`.

The intended use is to be able to watch a test suite with ghcid while creating it.

The first step is to add `testonly = True` which makes it possible to load tests targets in the REPL but then I didn't find a way to use `hspec-discover` so the test suites entrypoints don't get discovered.

**Comment by aherrmann** [comment]
Hi @aveltras, I think this should already be possible. Are you encountering any issues with this?

I've tested this out on a small example project and it seems to be working, see [here](https://github.com/aherrmann/example-servant-elm/compare/solution...test-repl?expand=1).
You can run `ghcid` on this using `ghcid --command="bazel run //server/test:repl" --test=Main.main`.
Changes to the tests in `server/test/AppSpec.hs` are picked up by ghcid as expected.

**Comment by aveltras** [comment]
Turns out you're right !

I did some useless things regarding getting `hspec-discover` in scope using nixpkgs toolchain.
Now that I just added it to the list of packages of ghcWithPackages, it becomes a non-issue (the previous error was related to `hspec-discover` not being available while adding tests suites to the repl target).

It's all good now. I'll close the issue.

Thanks again for your quick help !

**Comment by aveltras** [comment]
Seems I spoke too soon.

There seems to be a difference between the repl target and the test target.

The test target is `//hetchr-commons:test`.

I tested the REPL target by only adding the test target to its dependencies.

Either works depending of how the spec file is designed:

### Case A

`HetchrCommonsSpec.hs`

```haskell
{-# OPTIONS_GHC -F -pgmF hspec-discover -optF --module-name=HetchrCommonsSpec #-}
```

### bazel test //hetchr-commons:test

```sh
INFO: Analyzed target //hetchr-commons:test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
ERROR: /home/romain/Code/hetchr-product/hetchr-commons/BUILD.bazel:83:5: HaskellBuildBinary //hetchr-commons:test failed (Exit 1): ghc_wrapper failed: error executing command bazel-out/host/bin/external/rules_haskell/haskell/ghc_wrapper bazel-out/k8-fastbuild/bin/hetchr-commons/compile_flags_test_HaskellBuildBinary ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox ghc_wrapper failed: error executing command bazel-out/host/bin/external/rules_haskell/haskell/ghc_wrapper bazel-out/k8-fastbuild/bin/hetchr-commons/compile_flags_test_HaskellBuildBinary ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
ghc: could not execute: hspec-discover
Target //hetchr-commons:test failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.275s, Critical Path: 0.15s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
//hetchr-commons:test                                           FAILED TO BUILD

FAILED: Build did NOT complete successfully
```

### bazel run :repl

REPL loads fine with my test suite in scope.

### Case B

`HetchrCommonsSpec.hs`

```haskell
{-# LANGUAGE CPP #-}
{-# OPTIONS_GHC -F -pgmF HSPEC_DISCOVER -optF --module-name=HetchrCommonsSpec #-}
```

### bazel test //hetchr-commons:test

```sh
INFO: Analyzed target //hetchr-commons:test (0 packages loaded, 0 targets configured).
INFO: Found 1 test target...
Target //hetchr-commons:test up-to-date:
  bazel-bin/hetchr-commons/test
INFO: Elapsed time: 0.128s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
//hetchr-commons:test                                           (cached) PASSED in 0.0s

Executed 0 out of 1 test: 1 test passes.
INFO: Build completed successfully, 1 total action
```

### bazel run :repl

```sh
INFO: Analyzed target //:repl (0 packages loaded, 1 target configured).
INFO: Found 1 target...
Target //:repl up-to-date:
  bazel-bin/repl@repl
INFO: Elapsed time: 0.152s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
GHCi, version 8.10.4: https://www.haskell.org/ghc/  :? for help
ghc: could not execute: external/hspec-discover/bin/hspec-discover
ghc: could not execute: external/hspec-discover/bin/hspec-discover
Loaded GHCi configuration from /home/romain/.cache/bazel/_bazel_romain/9733998c2ddcf3d5c3fbec6a39de2342/execroot/hetchr-product/bazel-out/k8-fastbuild/bin/ghci-repl-script-repl
```

As you see, the repl breaks and no modules are loaded.

## More info

The `WORKSPACE `file contains:

```bzl
nixpkgs_package(
    name = "hspec-discover",
    attribute_path = "haskellPackages.hspec-discover",
    repository = "@nixpkgs",
)
```

The test targets are setup with the following `test` macro:

```bzl
def test(name, directory, deps, entrypoint = "Spec.main", polysemy = False):
    haskell_test(
        name = name,
        srcs = native.glob([directory + "/**/*.hs"]),
        src_strip_prefix = directory,
        main_function = entrypoint,
        tools = ["@hspec-discover//:bin"],
        plugins = ["polysemy_plugin"] if polysemy else [],
        data = native.glob(["test/data/**/*"]),
        compiler_flags = exts + ["-DHSPEC_DISCOVER=$(execpath @hspec-discover//:bin)"],
        deps = deps,
        tags = ["test"],
        visibility = [
            "//visibility:public",
        ],
    )
```

**Comment by aveltras** [comment]
@aherrmann 

I've created a minimal repo reproducing the issue encountered https://github.com/aveltras/bazel-nix-hspec-discover in case you want to have a look. 

Not sure if the problem is linked to the fact i'm not using the stackage functions but I think this should work without it too.

**Comment by aherrmann** [comment]
@aveltras Thank you for providing the minimal repo!

> Not sure if the problem is linked to the fact i'm not using the stackage functions but I think this should work without it too.

In a way: The issue here is that, from Bazel's perspective, the Nix provided `hspec-discover` is a *source* file in an external repository instead of a *generated* file in an external repository. This difference is important because the paths to those files are going to be different. A generated file is going to have an `execpath` starting with `bazel-out/.../bin` while a source file is going to have a path rooted at the execroot directly.

Translated to `hspec-discover`, with a Nix provided binary the `execpath` is `external/hspec-discover/bin/hspec-discover`, whereas with a Bazel built one it would be something along the lines of `bazel-out/host/bin/external/hspec-discover/bin/hspec-discover`. For build actions, e.g. building a `haskell_library`, this makes no difference. Bazel constructs the sandbox working dir such that both kinds of paths are valid. However, for the REPL this does make a difference, because the REPL is not executed in the sandbox working dir, but instead directly in the source repository (This is so that ghci reloads see source changes as expected). So, paths starting with `bazel-out` work just fine thanks to Bazel's creating convenience symlinks. But, paths starting with `external/...` do not work, as they don't exist in the source repository.

Generally, the REPL rule works around this using the [`RULES_HASKELL_EXEC_ROOT` env-var](https://github.com/tweag/rules_haskell/blob/b6242a0938323ee741e1dfa1a954d3f4360f1731/haskell/private/ghci_repl_wrapper.sh#L55). However, this only applies to paths generated by the REPL rule, not to paths set in user defined command-line flags. On top of that, these generally need to be [shell-escaped](https://github.com/tweag/rules_haskell/blob/b6242a0938323ee741e1dfa1a954d3f4360f1731/haskell/repl.bzl#L467-L470).

Perhaps a proper solution to this would be to add a `$RULES_HASKELL_EXEC_ROOT` prefix on `$(execpath)` expansion in flags for the REPL in some way.

In the mean-time. One possible workaround is to turn `hspec-discover` from a source file to a generated file. https://github.com/aveltras/bazel-nix-hspec-discover/commit/64b5220b6eb3270a1097ac7a14138783abb02f77 does this.

**Comment by aveltras** [comment]
@aherrmann Thanks, your workaround seems to work fine !

Not sure if you want to keep the issue open since you may be planning a fix in rules_haskell for this.
Feel free to close the issue if that's not the case as the problem is solved for me at least for now.

Thanks again for your help here !
