### ISSUE TITLE
"undefined reference" error with haskell_module

### ISSUE THREAD

**Issue by aherrmann** [tweag/rules_haskell#1612]
**Describe the bug**
Building a `haskell_test` with the dependency chain `haskell_test --> haskell_library --> haskell_module --> haskell_library` fails with an undefined reference error
```
ERROR: /home/aj/tweag.io/da/bazel-projects/rules_haskell/tests/haskell_module/library-dep/BUILD.bazel:36:13: HaskellLinkBinary tests/haskell_module/library-dep/library-dep failed: (Exit 1): ghc_wrapper failed: error executing command bazel-out/host/bin/haskell/ghc_wrapper bazel-out/k8-fastbuild/bin/tests/haskell_module/library-dep/compile_flags_library-dep_HaskellLinkBinary ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
bazel-out/k8-fastbuild/bin/tests/haskell_module/library-dep/libHStestsZShaskellZUmoduleZSlibrary-depZSModuleLib.a(TestModule.o):function testsZZShaskellZZUmoduleZZSlibraryzmdepZZSModuleLib_TestModule_bar_info: error: undefined reference to 'testsZZShaskellZZUmoduleZZSlibraryzmdepZZSTestLib_TestLibModule_foo_closure'
bazel-out/k8-fastbuild/bin/tests/haskell_module/library-dep/libHStestsZShaskellZUmoduleZSlibrary-depZSModuleLib.a(TestModule.o)(.data+0x58): error: undefined reference to 'testsZZShaskellZZUmoduleZZSlibraryzmdepZZSTestLib_TestLibModule_foo_closure'
collect2: error: ld returned 1 exit status
`cc_wrapper-python' failed in phase `Linker'. (Exit code: 1)
Target //tests/haskell_module/library-dep:library-dep failed to build
```

**To Reproduce**
Checkout https://github.com/tweag/rules_haskell/commit/d1fd2c4139dc3c84520e48093755709ab8268d85 and run
```
bazel build //tests/haskell_module/library-dep
```

**Expected behavior**
The build should succeed

**Environment**
 - OS name + version: Ubuntu 21.04
 - Bazel version: 4.1.0
 - Version of the rules: d1fd2c4139dc3c84520e48093755709ab8268d85 on top of latest `master` (4e38187e)

**Additional context**
The error message looks like the package-id is doubly z-encoded.

cc @Radvendii @facundominguez

**Comment by facundominguez** [comment]
Related to this, https://github.com/tweag/rules_haskell/pull/1644 is eliminating the deps attribute of haskell_module.

> A better error message would be good though. haskell_library should detect if it is missing any deps required by any of its modules

I don't see how to improve the error message without asking each module to list its dependencies on libraries exclusively for this sake. Note that when building, this is otherwise unnecessary since the dependencies of `haskell_library` are used to compile every module.

Keeping the list of dependencies in `haskell_module` up-to-date would also be a challenge. `gazelle_haskell_modules` used to copy the list of dependencies from the library to all of the modules without discriminating which modules needed which dependencies, and this resulted in bloated BUILD files. Which I don't think it is preferable to the current situation.

Is there anything we can do to improve matters?

**Comment by ylecornec** [comment]
Should this issue be closed ?

**Comment by facundominguez** [comment]
Fine with me. Leaving to @aherrmann to close it though.
