### ISSUE TITLE
Make main_file redundant where possible

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#168]
`main_file` is sometimes necessary, but currently we're relying on it being specified by the user in cases where we could as well have guessed the file with the `Main` module. The only time we don't need the `main_file` argument is when the file is called `Main.hs`. But if the source file's name starts with a lower-case letter, then it's not a valid module name and must surely be the Main module. So in this case, we shouldn't need the user to specify `main_file`.

**Comment by judah** [comment]
I've been thinking about this issue, and believe we can use `ctx.actions.declare_directory` to make `main_file` always redundant.  Namely, `declare_directory` for `-hidir` and -odir`, then look in those directories and use the found files to influence 

In fact, we can probably go even further and not require `src_strip_prefix`!  It turns out that `ghc --make` is pretty lenient in the directory structure of the module files.  The only caveat is that it still needs `-i` it for `hs-boot` files; so perhaps we should eventually rename that parameter to something like `hs_boot_imports`.

Some evidence for these assertions: the `cabal2bazel` rules for `haskell_library` and `haskell_binary` don't have an equivalent of `main_file` nor `src_strip_prefix`:
https://github.com/google/cabal2bazel/blob/771c522e0aee170b0ed488ad1bf198a5fc667ac5/bzl/def.bzl#L479
Those rules are older, so they solve the problem of not knowing the set of output files ahead of time by storing the results in a tarball ("archive").  Using the newer `ctx.actions.declare_directory` will probably help simplify the approach significantly.
https://github.com/google/cabal2bazel/blob/771c522e0aee170b0ed488ad1bf198a5fc667ac5/bzl/def.bzl#L634
https://github.com/google/cabal2bazel/blob/771c522e0aee170b0ed488ad1bf198a5fc667ac5/bzl/def.bzl#L534
https://github.com/google/cabal2bazel/blob/771c522e0aee170b0ed488ad1bf198a5fc667ac5/bzl/action.bzl#L176
