### ISSUE TITLE
Generate BUILD files from Cabal descriptions

### ISSUE THREAD

**Issue by jml** [tweag/rules_haskell#17]
## What 

A command-line tool to generate BUILD files from Cabal package descriptions.

Would behave similarly to the `gazelle` tool provided by https://github.com/bazelbuild/rules_go

### Supporting dependencies

- the vast majority of existing Haskell code uses Cabal
- to use these projects as dependencies of a Bazel project requires they each have BUILD files
- writing those files by hand is tedious & error-prone

### Migrating to Bazel

- People who want to start using Bazel will have a much easier time of it if there is a tool to help them migrate

### Maintaining Haskell Bazel projects

- Bazel works best with fine-grained dependencies—more opportunity for parallelism, less to rebuild when things change
- It's very common to change the dependencies of a module when writing code
- It would be great if you could just run a tool to update the BUILD file when this happens

### Complicated dependencies

- A lot of Haskell code depends on C libraries, which could theoretically be built in Bazel
- Rather than many human beings re-learning how to do this, how about we encode the knowledge in a computer program?

The exact details & design of this tool need to be fleshed out. I would suggest closing this ticket once there's a minimal tool that handles the common 80% use case and filing follow-ups for the rest.

**Comment by Fuuzetsu** [comment]
I think we need both the fine-grained mode where dependency graph inside a library is considered and coarse mode which just feeds the whole library to GHC at once. The former is potentially useful for frequently changing components but incurs large performance hit from GHC (compiling modules 1 by 1 is slow) while the latter can be much quicker if we're going to be compiling everything anyway.

There's a question of how to discover the dependency graph. There are multiple ways to do this:

* parse `ghc -M` output. This spits out a makefile we can read into a graph.
* use GHC API: this is potentially much more flexible and we don't have to fiddle with parsing stuff ourselves but it requires continuous effort to keep updated for new and old GHC versions. In principle this is the right way to do it though.
* use a third party tool like haskell-src-exts and build a graph from whatever the tool gives us

All of these have the same common problem of "what happens if file needs preprocessing?"; for example if you have CPP on module imports based on library versions. This is pretty common. We might need to do something non-trivial here.

Other questions are things like dealing with data files (easy-ish in bazel), cabal file flags (potentially quite difficult…), Paths_… It's also unclear how to generate dependency fields: currently we allow wired-in packages that GHC can automagically find and there's no good way to disambiguate what should count as wired-in and what should count as bazel dependency. Indeed we can't really map a Haskell dependency to a bazel dependency at all, it can live anywhere in the project.

List of stuff goes on, for MVP I would suggest:
* parse out module list from cabal file
* find all the associated source files: this has to include cpphs, hsc, lhs
* don't worry about depgraph at all, build everything as one chunk for now
* work on C files: include-dirs, c-sources, cc-options, includes and install-includes should all be supported. Building multiple languages in a project is The Killer Feature™ so let's try to support something here for MVP
* every listed haskell dependency goes into `prebuilt_dependencies` (in #14 language)
* we should generate entries for test suites and benchmarks too
* let's not worry about cabal flags to start with but lets omit things with trivially discoverable `buildable: False`; if we can get Cabal to spit out a processed file with all the default flags applied, that's a lot easier

Let me know what you think

**Comment by jml** [comment]
That's a pretty good MVP list. 

> I think we need both the fine-grained mode where dependency graph inside a library is considered and coarse mode which just feeds the whole library to GHC at once. The former is potentially useful for frequently changing components but incurs large performance hit from GHC (compiling modules 1 by 1 is slow) while the latter can be much quicker if we're going to be compiling everything anyway.

Agree we need both. We probably need some way to allow "coarse" or "fine" to be specified per-package, and for that choice to be preserved in subsequent runs of the generator tool.

I spoke to some Standard Chartered folk at Haskell Exchange 2017, and they said they really wanted fine-grained dependency builds, because for them the biggest limit was parallelism.

**Comment by jml** [comment]
Here's what I have already come up with: https://github.com/jml/rules_haskell/tree/cabal-to-bazel/haskell/tools/cabal-to-bazel

IIRC, it will do fine-grained Haskell-only BUILD file (no C) for goldilocks packages. Current version won't compile, but `HEAD^` ought to print something under some circumstances.

I took the approach of going via the Cabal APIs. Most of the work involved was figuring out what the heck those actually were (I'm not fully across the 2.0/backpack changes), and deciphering Cabal's model. 

I still think it's the right approach. Cabal already knows (at some level) how to turn Haskell projects into a series of `ghc` invocations, so it's a good fit for turning build rules into actions. If we don't use Cabal, we'll end up duplicating large chunks of its logic. (Evidence: even `stack` uses Cabal)

OTOH, Cabal has a pretty complicated conditions framework for solving the same problem as Bazel platforms & selects. Mapping from one to the other might be harder than re-implementing Cabal stuff.

I also got stuck on how deep to go. Should `cabal-to-bazel` work for `base`? `ghc-prim`? What would that even mean? Which packages can I 100% absolutely rely on as being available w/ GHC?

This was a problem because my goal was to get to self-hosting as fast as possible, and I didn't have anyone to talk to who could say "stop worrying and just pick something".

FWIW, I think `hazel` could be a good name for this tool. I picked `cabal-to-bazel` because my daughter's name is Hazel, and I didn't want her to think I was upset with her while I'm angrily muttering at my computer.

**Comment by Fuuzetsu** [comment]
I agree on using Cabal-the-library. It ships with GHC anyway.

>I also got stuck on how deep to go. Should cabal-to-bazel work for base? ghc-prim? What would that even mean? Which packages can I 100% absolutely rely on as being available w/ GHC?

See wired-in libraries section at https://ghc.haskell.org/trac/ghc/wiki/Commentary/Libraries . However in general I think you still want to be able to build and use things like `base`: consider when you want to do profiling, you need profiled `base`. For MVP I would hardcode these wired-in packages to not generate anything as work in rules_haskell will be likely required in order to make those work alongside existing packages shipped with GHC itself.

`hazel` is a nice name, I like it.

**Comment by mboes** [comment]
Closing, since I think https://github.com/formationai/hazel works quite well now and should satisfy most of the requirements in this ticket. To the extent that they don't, that should lead to further tickets in the Hazel issue tracker.
