### ISSUE TITLE
Shared libraries have too many dependencies on Mac

### ISSUE THREAD

**Issue by facundominguez** [tweag/rules_haskell#1714]
One difference between `stack` and `rules_haskell` in Mac is that the former uses the linker flag `-dead_strip_dylibs` to keep the amount of load commands low. To fix #170, `rules_haskell` started discarding `-dead_strip_dylibs` in #627.

This however is causing some libraries to exceed a limit of 254 load commands, which is imposed by how MachO file format deals with two-level namespaces and library ordinals. The description of the `n_desc` field in [this source](https://github.com/aidansteele/osx-abi-macho-file-format-reference/blob/master/README.md#nlist_64) indicates the limit.

Looks like we would need either to recover our ability to use `-dead_strip_dylibs` or to start splitting libraries in an attempt to keep the count of load commands low. 

**Environment**
 - OS name + version: Mac
 - Bazel version: 5
 - Version of the rules: 0.14

## Why do we need to discard `-dead_strip_libraries`?

cc libraries underlink in `bazel`, which means that they don't report all of their dynamic dependencies, and `bazel` keeps track of the transitive dependencies to use them when linking a cc binary.

When cc libraries are used in a haskell library, `rules_haskell` links all of the transitive dependencies of the cc libraries, so they don't need to be tracked separately. However, when `-dead_strip_dylibs` is enabled, it has the effect of discarding all of the indirect dependencies, including indirect cc dependencies which aren't otherwise declared to the dynamic loader. This would cause missing undefined symbols when trying to run binaries which use the haskell libraries, which use cc libraries, which depend on other cc libraries that have been stripped.

A possible fix would be to stop linking indirect cc dependencies in Haskell libraries, and collect them to link them in haskell binaries and tests instead. This is implementing in `rules_haskell` the same linking strategy for cc dependencies as cc rules use.

**Comment by aherrmann** [comment]
> A possible fix would be to stop linking indirect cc dependencies in Haskell libraries

A concern with this is that GHC may still require the complete set of transitive C library dependencies in a Haskell library, e.g. for template Haskell or GHCi. So, this may break some builds.

> A possible fix would be to stop linking indirect cc dependencies in Haskell libraries, and collect them to link them in haskell binaries and tests instead. This is implementing in `rules_haskell` the same linking strategy for cc dependencies as cc rules use.

To clarify, is it really too many C library dependencies exceeding the number of load commands? Or is it too many load commands in total, and (transitive) Haskell libraries are likely the larger contributor to that total?

I'm asking, because if the issue comes from too many Haskell library dependencies, then it seems that changing the linking of C libraries will not resolve the issue and instead the issue is that disabling `-dead_strip_dylibs` is too blunt, because it affects both C and Haskell dependencies. We'd want the same effect for C library dependencies, but for Haskell dependencies we only want to link direct dependencies, because Haskell libraries are not underlinked.

One option that we used in the past was to [pass `-u` flags](https://github.com/tweag/rules_haskell/pull/627/files#diff-4d38b8f66d4db71dfabed56e111ad4b98985db124fdce4efeaa4467338815003R102) for symbols from libraries to enforce linking these libraries. It's a bit hacky, so perhaps there's a better solution. But, something along those lines may solve this issue: I.e. link all transitive C library dependencies, but only direct Haskell library dependencies.

**Comment by facundominguez** [comment]
> A concern with this is that GHC may still require the complete set of transitive C library dependencies in a Haskell library, e.g. for template Haskell or GHCi. So, this may break some builds.

Good point. This would call for passing all the cc libraries to GHC when TH is enabled.

> Or is it too many load commands in total, and (transitive) Haskell libraries are likely the larger contributor to that total?

Dependencies on Haskell libraries represent the 95% of all the load commands.

> I'm asking, because if the issue comes from too many Haskell library dependencies, then it seems that changing the linking of C libraries will not resolve the issue

I think it will resolve the issue because then it would allow us to re-enable `-dead_strip_dylibs`. If we link all the cc libraries when linking binaries, at least they won't be stripped when linking Haskell libraries.

> One option that we used in the past was to pass -u flags

Wouldn't `-u` still cause load commands for transitive dependencies to be included?

**Comment by aherrmann** [comment]
> Wouldn't `-u` still cause load commands for transitive dependencies to be included?

Yes, but it can be done selectively. The C libraries are underlinked, so with them we actually want to link all transitive deps. With this we'd have the control to link all the transitive C libraries but only the needed Haskell libraries.
