### ISSUE TITLE
`find_cc_toolchain` error when building `//tests:protocwrapper.cmd`

### ISSUE THREAD

**Issue by Wyverald** [tweag/rules_haskell#1963]
**Describe the bug**
On Bazel 6.3.2, trying to build `//tests/...` fails with the following message:

```
ERROR: /usr/local/google/home/wyv/github/rules_haskell/tests/BUILD.bazel:13:15: in _protoc_wrapper rule //tests:protocwrapper.cmd: 
Traceback (most recent call last):
	File "/usr/local/google/home/wyv/github/rules_haskell/tests/protoc.bzl", line 10, column 27, in _protoc_wrapper_impl
		cc = find_cc_toolchain(ctx)
	File "/usr/local/google/home/wyv/.cache/bazel/_bazel_wyv/3a07f8d42f5e075b1524c733ca45f269/external/rules_cc/cc/find_cc_toolchain.bzl", line 87, column 9, in find_cc_toolchain
		fail("In order to use find_cc_toolchain, your rule has to depend on C++ toolchain. See find_cc_toolchain.bzl docs for details.")
Error in fail: In order to use find_cc_toolchain, your rule has to depend on C++ toolchain. See find_cc_toolchain.bzl docs for details.
ERROR: /usr/local/google/home/wyv/github/rules_haskell/tests/BUILD.bazel:13:15: Analysis of target '//tests:protocwrapper.cmd' failed
ERROR: Analysis of target '//tests:protocwrapper.cmd' failed; build aborted: 
```

This test was added in https://github.com/tweag/rules_haskell/commit/fc33feff414b7ab4035932d023078d97356fffea

**To Reproduce**
`USE_BAZEL_VERSION=6.3.2 bazel build //tests/...`

**Expected behavior**
Nothing fails.

**Environment**
 - OS name + version: Debian rolling
 - Bazel version: 6.3.2
 - Version of the rules: HEAD

**Additional context**
rules_haskell is red on Bazel CI.

**Comment by avdv** [comment]
Seems like the changes in #1964 did not have the desired effect as this is still failing with the same error on Buildkite (https://buildkite.com/bazel/rules-haskell-haskell/builds/1696).

And I am even more confused than before, since we were using:
```bazel
toolchains = ["@rules_cc//cc:toolchain_type"],
```
which worked on our CI, `@rules_cc//cc:toolchain_type` being an alias to `@bazel_tools//tools/cpp:toolchain_type`. Now, we're instead using:
```bazel
    toolchains = use_cc_toolchain(),
```
but this also does not work :confused: ?

Any ideas? @aherrmann
