### ISSUE TITLE
Error no such attribute 'exec_constraints' in '_nixpkgs_package' rule

### ISSUE THREAD

**Issue by sgowroji** [tweag/rules_haskell#1972]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3358#018b0302-f6e0-4559-98a1-78e403376c4d

Platform : Ubuntu

Logs:
```
bazel --nosystem_rc --nohome_rc info
ERROR: /var/lib/buildkite-agent/builds/bk-docker-87wf/bazel-downstream-projects/rules_haskell/WORKSPACE:51:13: //external:rules_haskell_sh_posix_nixpkgs: no such attribute 'exec_constraints' in '_nixpkgs_package' rule
ERROR: error loading package '': Encountered error while reading extension file 'os_info.bzl': no such package '@os_info//': error loading package 'external': Could not load //external package
```

Steps:
```
git clone -v https://github.com/tweag/rules_haskell.git
git reset f801bba2773ae2fde30e0da2138f6ac0f2c2a910 --hard
export USE_BAZEL_VERSION=7dcb57511be1553fe46e2f54cdbd0969d7c76c4b
bazel --nosystem_rc --nohome_rc version
```

CC Greenteam @salmasamy

**Comment by avdv** [comment]
We already fixed this issue [here](https://github.com/tweag/rules_nixpkgs/pull/418) and upgraded rules_nixpkgs in this repository in #1965, which was merged to master on 26th Sep.

The Buildkite check used an old commit (f801bba2773ae2fde30e0da2138f6ac0f2c2a910) from rules_haskell, instead of the HEAD - I suppose since it uses the last green commit which seems to be broken currently: 

https://buildkite.com/bazel/rules-haskell-haskell/builds/1738#018b35dc-49e9-4388-94d7-aee9e942b871

The reason being that it tries to run the shellcheck checks, despite the `--test_tag_filters` containing `-requires_shellcheck`. :eyes: 

Oh, `--test_tag_filters` get overridden and don't accumulate usages. That's https://github.com/bazelbuild/bazel/issues/7322

**Comment by avdv** [comment]
Since #1973 was merged and bazel CI updated the last green commit successfully, the latest Bazel@HEAD [run](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3391#018b3bcb-68aa-4987-9304-53f1d05f0529) does not fail with the error any more (but fails in a different way, go figure).

**Comment by avdv** [comment]
> Hi @avdv, I still see the CI is failed [buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3396#018b40f1-d042-4957-b897-17f2c6629c8d](https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3396#018b40f1-d042-4957-b897-17f2c6629c8d). Can you please take a look. Thanks!

That's a different error taken care of by #1980. Hopefully it will work tomorrow... :crossed_fingers:  BTW, is there an easy way to run the Bazel@HEAD pipeline myself on this project? Otherwise the feedback loop is quite long.
