### ISSUE TITLE
Conflict between haskell_libraries with the same name in different directories

### ISSUE THREAD

**Issue by judah** [tweag/rules_haskell#219]
Example:
https://github.com/tweag/rules_haskell/commit/90390580ed314716bfb532cb3a25ea2262586a4a

A binary depends on two `haskell_library` rules with the same name: `tests/library-deps/sublib:sublib` and `tests/library-deps:sublib`.  This fails:
```
bazel build tests/library-deps:bin
```
It conflicts with tests/library-deps/sublib:sublib; in fact,
renaming one of the `sublib` rules to, e.g., `...:sublibA` lets the build succeed.

The relevant code is here: https://github.com/tweag/rules_haskell/blob/9a2ba48e737ae06e3d448d8e4baf1cdd36dbc28c/haskell/actions.bzl#L784

We should be able to change that function to make a package name that includes the ctx.label's package and workspace_root. (I'm not sure at the moment whether we'd need to escape slashes like we do here: https://github.com/tweag/rules_haskell/blob/9a2ba48e737ae06e3d448d8e4baf1cdd36dbc28c/haskell/actions.bzl#L88)

**Comment by mrkkrp** [comment]
Here is a potential fix: https://github.com/tweag/rules_haskell/commit/f26cca4977cedf0f3b09e8930aa752fe1b31b076.

@judah @mboes I discovered that GHC does not allow underscores or two dashes in a row in package names, so using `-U-` as delimiter between Bazel package and component name looks like a good-enough option. What do you think?

(The CI failures is because we need to adjust the names of generated files in all the tests, so before starting with this boilerplate I decided to settle with what to use as the delimiter.)

**Comment by judah** [comment]
@mrkkrp, we should also take into account the `workspace_root` of the label, not just the package:
https://docs.bazel.build/versions/master/skylark/lib/Label.html#workspace_root

I also think the `ctx.label.package.replace('/','-')` is not disambiguating enough; for example, the following two labels would map to the same package name: `//foo-test:bar` and `//foo/test:bar`.  See: https://docs.bazel.build/versions/master/build-ref.html#package-names-package-name

**Comment by mrkkrp** [comment]
The problem here is that this thing, package id, should be a valid package id that GHC accepts. GHC however does not accept underscores or any tricky things like two dashes in a row. In other words, there is no way to achieve injectivity here because the set of names GHC accepts is smaller than the set of possible package names. Which means, we will lose some information when we obtain GHC package id from bazel package name, which means there will always be potential for ambiguity.

That said, this is a good catch by @judah, I'm already experimenting with this. So far I think we indeed could use something similar to that existing mangling function:

* `_` -> `-uU-`
* `/` -> `-sU-`
* and we need something better than `-` to separate package name and target name so things like `//foo-bar:baz` and `//foo:bar-baz` don't clash.

Note that still, particularly perverted package names will have the potential for clashing, e.g. I can have two packages: `foo/bar` and `foo-sU-bar` still.

**Comment by mboes** [comment]
> In other words, there is no way to achieve injectivity here because the set of names GHC accepts is smaller than the set of possible package names.

Of course we can! GHC's z-encoding is an example of that: linkers only want `[A-Z]` characters in sames so anything else (underscores, hyphens etc) is encoded *injectively* to that character set.

**Comment by Fuuzetsu** [comment]
Or we could just require unique package names. It's not really any different from existing systems.

**Comment by mboes** [comment]
@Fuuzetsu I think what @judah is going for is very fine-grained targets, in which case reusing generic target names in packages could be very convenient.
