### ISSUE TITLE
Add a "haskell_repl" executable

### ISSUE THREAD

**Issue by judah** [tweag/rules_haskell#220]
Currently, in order to use a REPL, we need to write explicit `haskell_repl` rules.  Compare that to the UX of stack or cabal, where you can write `stack repl some-package`, `stack repl some-package:exe:some-binary`, etc., and automatically load a session with all the source files and dependencies for a particular target.

An alternate approach would be for `rules_haskell` to provide a single, generic script that takes a Bazel target (or targets) as a command-line argument, for example:
```
bazel build @io_tweag_rules_haskell//haskell_repl
bazel-bin/external/io_tweag_rules_haskell/haskell_repl/haskell_repl //some/haskell:target
```

One approach would be to write a version of `haskell_repl`  which is an [aspect](https://docs.bazel.build/versions/master/skylark/aspects.html#invoking-the-aspect-using-the-command-line), and then make the above script call `bazel build //some/haskell:target --aspects ...` to generate the script that the explicit rule produces today.

Another approach would be to use an [OutputGroup](https://docs.bazel.build/versions/master/skylark/rules.html#requesting-output-files) for each `haskell_library`/`haskell_binary`, which contains source files and compilation info (similar to what we pass through the existing providers (`HaskellBuildInfo`, `HaskellLibraryInfo`).

**Comment by johnynek** [comment]
you could make a repl target an optional output of all rules.

e.g.

`bazel run --direct_run //foo/bar/baz.repl`

**Comment by mrkkrp** [comment]
I worked on this today: https://github.com/tweag/rules_haskell/compare/auto-repl-per-target. @johnynek's idea worked quite well, we define optional repl output automatically for every binary and library target and so it's not built till explicitly requested.

Not opening PR yet because this needs:

* a small cleanup
* docs update
* adding some options, such as something for setting additional GHCi flags, we provided this previously
* a re-do of testing

I'll finish this up on Wednessday.
