### ISSUE TITLE
Encoding issues during compilation

### ISSUE THREAD

**Issue by mrkkrp** [tweag/rules_haskell#313]
The way `ghc` is currently invoked there is a possibility of encoding issues. For example if we load a file via TH and that file contains unicode characters, the following error is shown:

```
hGetContents: invalid argument (invalid byte sequence)
```

We need to find a way to ether set environment variable `LANG` manually or to forward host settings.

**Comment by mboes** [comment]
The proper thing to do here is probably forwarding host settings. Because that way e.g. French users will get at least some error messages in French. The problem is, we lower the cache hit rate if we do that, since the environment is part of the lookup key in the action cache. Some users have `en_US.utf8` and some have `en_UK.utf8` or myriad other locales even for just English. So I guess... hard code `LANG=en_US.utf8`? I feel dirty...

It would be nice if there was a generic utf8 locale, like the `C` locale.

**Comment by iphydf** [comment]
If host env var forwarding happens, I'd like a way to manually override that in e.g. WORKSPACE, because I care a lot about hermeticity and shareability of build artifacts. We build on many developer machines with different environments, but we share one remote build cache.

**Comment by mrkkrp** [comment]
This is actually already resolved by #328, and yes, you can set things explicitly.
