### ISSUE TITLE
add something like include_prefix

### ISSUE THREAD

**Issue by ghorn** [tweag/rules_haskell#341]
For C/C++, bazel has https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library.include_prefix and https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library.strip_include_prefix for adding or stripping prefixes for later `#include`s.

I believe for Haskell we only have one of those: https://haskell.build/haskell/haskell.html#haskell_binary.src_strip_prefix. It would be nice to also have the other.

**Comment by mboes** [comment]
Interesting idea. How would you like this to work? Something like the following?

```
import Foo.Bar
```

becomes 

```
import My.Corp.Foo.Bar
```

if `import_prefix = "My.Corp"`?

Note that `src_strip_prefix` doesn't affect the import path like `strip_include_prefix`. It's more akin to say `strip_prefix` in `http_archive`.

**Comment by Profpatsch** [comment]
I can’t see how this should work in Haskell either; in C(++) you need these prefixes, since headers are referenced by their folder and oftentimes not exactly where the imports say they are (that is missing or having an additional prefix), but in Haskell there’s one global module structure with absolute module names.
The only thing our author could want to change in a build rule is to specify where this module structure should start for the current package, which should be fully handled by `src_strip_prefix` (given the bazel author never wants to go upwards from the source folder, but I can’t see why they would want that).

**Comment by Profpatsch** [comment]
Stripping/Adding a module name prefix can also be done manually once we implement https://github.com/tweag/rules_haskell/issues/358

**Comment by ghorn** [comment]
> `import Foo.Bar`
> becomes
> `import My.Corp.Foo.Bar`

Yes that's what I had in mind.

> in C(++) you need these prefixes, since headers are referenced by their folder and oftentimes not exactly where the imports say they are (that is missing or having an additional prefix), but in Haskell there’s one global module structure with absolute module names

Yeah this doesn't seem like the best idea anymore.

**Comment by Profpatsch** [comment]
Thanks, I will close.
