### ISSUE TITLE
Multi-package repl

### ISSUE THREAD

**Issue by regnat** [tweag/rules_haskell#380]
Rules haskell provides `-repl` targets to open custom repls, so that if I have a target `:foo`, I can `bazel run //:foo-repl` to open a ghci session with all of `foo` available (like `stack repl foo`). However if I have two targets `:foo` and `:bar`, there's no way to open a ghci session with both `foo` and `bar` (like `stack repl foo bar` would do).

**Comment by shmish111** [comment]
To be clear, what would be great is if all dependencies that are themselves workspace targets would be loaded directly from their source code rather than from compiled targets. 

I think this would mean that if I am working on `Bar.hs` in haskell_library `A` that depends on `Foo.hs` in haskell_library `B` and I change `Foo` then when I `:r`, the changes that occurred in `Foo` are available to `Bar`. At least that's the behaviour that I am looking for for a development workflow.

**Comment by shmish111** [comment]
Additionally, it would be great to have the option to not load any files initially, stack has this option. This is because in an IDE situation, you want the repl to load as quickly as possible and you probably don't need it to compile everything in your project. Instead you will load one file and that will trigger all the dependencies in it's dependency tree to be compiled only.

**Comment by dajmaki** [comment]
I did a quick try to see if I could use the existing repl mechanisms to load sources of multiple packages:
https://github.com/dajmaki/rules_haskell/tree/experiment-haskell-repl

With this you define a repl target:
```haskell_repl(name = "combined", deps = ["//:libraryA", "//:libraryB"])```.
This creates a ghci script that loads the sources of both libraryA and libraryB, and package dependencies from both should be loaded. I haven't tested it heavily and don't know what the shortcomings are.

Thoughts on this approach? Any obvious issues?

**Comment by dajmaki** [comment]
It loads the source files (though looks like the package dbs for both are passed to ghci as well so it does need a bit more work...)
