### ISSUE TITLE
ghc_bindist fails on Nixos (not clear what needs to be in PATH)

### ISSUE THREAD

**Issue by aspiwack** [tweag/rules_haskell#506]
Well, it fails on _my_ Nixos. It seems that `ghc_bindist` needs to slurp a bunch of things from the path. First it needs `ar` to unpack the archive.  After adding `ar` in a `nix-shell` I get:

```
utils/ghc-cabal/dist-install/build/tmp/ghc-cabal-bindist: line 3: /home/aspiwack/.cache/bazel/_bazel_aspiwack/62d852aed851e65edffeca0c3b4d5153/external/ghc/utils/ghc-cabal/dist-install/build/tmp/ghc-cabal: No such file or directory
make[1]: *** [ghc.mk:990: install_packages] Error 127
make: *** [Makefile:51: install] Error 2
```

Which I didn't take time to follow up on yet.

The bottomline is that it's unclear what the requirements for bindist are (also, it's not clear why stack can install ghc without external dependencies and rules_haskell cannot).

**Comment by mboes** [comment]
Because Stack doesn't use a bindist on NixOS. It implicitly turns on `--nix` on that platform. Bindists _never_ work on NixOS, by design of that platform. It's a design that sets it apart from every other platform out there (non-standard linker location). This is documented on the [NixOS wiki](https://nixos.wiki/wiki/Packaging/Binaries).

Stack won't work if you tell it explicitly to use a bindist. Every other rule set won't work if you tell it explicitly to use a bindist. The solution is to not specifically tell rules_haskell to download a bindist. Use rules_nixpkgs instead. It's the only option. Just like Stack _must_ use `--nix` on NixOS.

**Comment by aspiwack** [comment]
Ah yes… But unless tweag/rules_nixpkgs#54 has a solution, that requires an extra dependency. I don't suppose there is a way to switch behaviour in the WORKSPACE depending on the underlying system like Stack does?

**Comment by regnat** [comment]
That could be triggered by a CLI flag with [select](https://docs.bazel.build/versions/master/be/functions.html#select) (which itself could be put in the user's `~/.bazelrc` to avoid repeating it each time)

**Comment by regnat** [comment]
Or maybe [platforms](https://docs.bazel.build/versions/master/platforms.html#defining-constraints-and-platforms) would be a better mechanism for that? I don't really understand how it works, but

> Modeling the environment as a platform helps Bazel to automatically select the appropriate toolchains for build actions
