### ISSUE TITLE
Select a ghc_bindist as the haskell toolchain for tests on Windows

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#559]
The rules_haskell test suite unconditionally uses a GHC provided by Nixpkgs. On Windows, Nixpkgs is unavailable. So we should define the toolchain in such a way that if we are on Windows, a `ghc_bindist()` rule is used instead of the current `nixpkgs_package()`. See [select] and [platforms](https://docs.bazel.build/versions/master/platforms.html) for this (see [example here](https://github.com/bazelbuild/rules_go/blob/master/go/core.rst#platform-specific-dependencies)).

**Comment by nmattia** [comment]
Here's a branch with a test suite that simply summons GHC (without trying to compile any Haskell: https://github.com/tweag/rules_haskell/compare/nm-simple-ghc-tests

It
* Provides a Go SDK on Windows
* Use a GHC bindist on Windows
* Adds a `ghc --help` test

This unfortunately breaks because:

> ERROR: Analysis of target '//tests/ghc:ghc_help' failed; build aborted: no such package '@hackage-ghc//': The repository could not be resolved

Even though a `@hackage-*`-free branch is used in the `select`, somehow `Bazel` tries to evaluate `@hackage-ghc`.
