### ISSUE TITLE
Haskell dependencies as a toolchain?

### ISSUE THREAD

**Issue by aspiwack** [tweag/rules_haskell#582]
I've been thinking about the Haskell dependencies and Nix vs Hazel.

Currently, they are so distinct that they use different syntax. But at the end of the day, they serve the same purpose. And you may consider switching between them as the project changes, or simply between platforms (you may want to use `rules_nixpkgs` on Linux, but rely on Hazel for Windows build, typically).

I think that, philosophically, my BUILD files should be unconcerned with how I get my dependencies. This should be decided in my WORKSPACE somehow.

So here is the thought: is it imaginable, at all, that we publish Haskell dependencies as toolchains (the pkgdb being one, and Hazel being another). That would require a uniform interface for the both of them, though.

Thoughts?

**Comment by mboes** [comment]
This was proposed here: https://github.com/tweag/rules_haskell/issues/75#issuecomment-354722084.

**Comment by Profpatsch** [comment]
Do we intend to move in this direction? I like the idea of external Haskell packages being “just another bazel dependency”, which is contrary to “pushing everything into the toolchain”.

In practice pushing everything to the toolchain also means that you lose granularity (and thus build and cache speed), because you must rebuild everything that depends on the toolchain if one single dependency changes.

**Comment by mboes** [comment]
We've moved closer to this with `haskell_toolchain_library`, which makes a toolchain provided library largely indistinguishable from a Bazel-built library. In parallel to that, we're moving away from Nixpkgs-provided libraries, because we have a good alternative with `haskell_cabal_library`.
