### ISSUE TITLE
Check that declared version in haskell_toolchain matches

### ISSUE THREAD

**Issue by mboes** [tweag/rules_haskell#61]
The user supplies a version number to `haskell_toolchain`. The user also provides a label locating a GHC install. We should check (at runtime) that the supplied GHC matches the expected version. For more user-friendly errors in case of a mismatch.

**Comment by jbgi** [comment]
If the version is needed, why not just take the output of `ghc --numeric-version`, thus sparing user to duplicate the version both for nix and bazel?

ie. Could we remove the requirement for the `version` attribute of `haskell_toolchain`?

**Comment by guibou** [comment]
@jbgi Really good point, we where discussing this recently.

Due to bazel internals, it is not simple to take the output of `ghc --numeric-version` and use it internally in `rules_haskell`. I'm still looking for a satisfying solution. If you think this is an important task, please open a new issue and affect me to it.
