### ISSUE TITLE
Bazelify libgmp

### ISSUE THREAD

**Issue by nmattia** [tweag/rules_haskell#718]
To assess whether it is worth having libgmp provided through bazel (see https://github.com/tweag/rules_haskell/issues/704#issuecomment-466967360) the following options should be investigated:
1. Use https://github.com/robin-thomas/bazelify-gmp
1. Have a simple, non-modular (e.g. "quick and dirty") libgmp bazel repository

**Comment by mboes** [comment]
Before doing this, figure out whether this is needed at all (see #704). If the bindists want something on the system, we should let the bindist grab what it thinks it needs from the system. Overriding with our own supplied libraries may or may not be a good idea.

**Comment by mboes** [comment]
This can't be easily done. `bazelify-gmp` won't help because `ghc_bindist` is a workspace rule, and needs libgmp available from the configure phase (i.e. during workspace rule execution). So libgmp needs to be a workspace repo, and it needs to either be prebuilt (where?), or we build it during workspace rule execution, but then we don't get any decent caching (and no sandboxing). On balance, I think it's better to let libgmp be picked up from the system.
