### ISSUE TITLE
Allow some libraries to be used in place instead of symlinking them?

### ISSUE THREAD

**Issue by facundominguez** [tweag/rules_haskell#782]
**Is your feature request related to a problem? Please describe.**

I've tried to execute a test with `bazel run //:spec`. The test depends on `libjvm.so`. No matter what I try, bazel ends up putting a symlink to `libjvm.so` in the runfiles of the test. For instance: 
```
bazel-out/k8-fastbuild/bin/spec.runfiles
├── io_tweag_inline_java
│   ├── _solib_k8
│   │   ├── _U_S_S_Copenjdk___Uexternal_Sopenjdk_Slib_Sopenjdk_Sjre_Slib_Samd64
│   │   │   └── libjava.so -> /home/centos/.cache/.../libjava.so
│   │   ├── _U_S_S_Copenjdk___Uexternal_Sopenjdk_Slib_Sopenjdk_Sjre_Slib_Samd64_Sserver
│   │   │   └── libjvm.so -> /home/centos/.cache/.../libjvm.so
│   ├── spec -> /home/centos/.cache/.../bin/spec
│   └── Spec.hs -> /home/centos/.cache/.../genfiles/Spec.hs
└── MANIFEST
```

This in turn, causes `libjvm.so` to look for `libjava.so` at a location where it is not present:
```
$ bazel run //:spec
...
Executing tests from //:spec
-----------------------------------------------------------------------------
Error occurred during initialization of VM
Unable to load native library: /home/centos/.cache/bazel/_bazel_centos/589e581f43ed24e379c7bd0e2ec
2d636/execroot/io_tweag_inline_java/bazel-out/k8-fastbuild/bin/_solib_k8/libjava.so: cannot open s
hared object file: No such file or directory
```

`libjava.path` is present in the RUNPATH, but it is not searched there. 

```
$ objdump -x bazel-out/k8-fastbuild/bin/spec | grep RUNPATH     RUNPATH              $ORIGIN/_solib_k8/_U_S_S_Copenjdk___Uexternal_Sopenjdk_Slib_Sopenjdk_Sjre_Slib_Samd64_Sserver:$ORIGIN/_solib_k8/_U_S_S_Copenjdk___Uexternal_Sopenjdk_Slib_Sopenjdk_Sjre_Slib_Samd64:$ORIGIN/_solib_k8/_U_S_Sjni_Copenjdk___Uexternal_Sopenjdk_Slib_Sopenjdk_Sjre_Slib_Samd64_Sserver:$ORIGIN/_solib_k8/_U_S_Sjni_Copenjdk___Uexternal_Sopenjdk_Slib_Sopenjdk_Sjre_Slib_Samd64:/nix/store/q8rg4mca5zqv98arpxd7164pqa72hf1n-ncurses-6.1/lib:/nix/store/hhzvw77vrmn5f506kfyb1yh1sdinkbwf-gmp-6.1.2/lib:/nix/store/83lrbvbmxrgv7iz49mgd42yvhi473xp6-glibc-2.27/lib:/nix/store/zikcg4s36w5k6fvlba2h4p4riw1qc7fp-gcc-7.3.0-lib/lib
```

`libjvm.so` does not list `libjava.so` in the ELF dependencies. It is opened with a `dlopen` call.
Looking at the source code in the jdk, it seems to find the path of `libjvm.so`, and load `libjava.so` from `$(dirname path/to/libjvm.so)/../libjava.so`.

This can be tested with the repo in https://github.com/tweag/inline-java/tree/fd/update-bazel with bazel 0.22.

**Describe the solution you'd like**
Ideally, we would have some way to link the real path of libjvm.so instead of linking a symlink.

**Comment by facundominguez** [comment]
We are going to try to solve the case for the jvm, by copying the necessary libraries in the way that libjvm.so wants it with a genrule or a custom rule.

**Comment by Profpatsch** [comment]
In general you cannot do that with bazel, because runfiles are implemented with symlinks on Linux (they aren’t on Windows!).

You should make sure that you don’t break the implicit hermeticity assumptions, because bazel won’t containerize runtime stuff for you. Meaning: The symlinks point to some file, but that file is in a directory that might contain files from other targets. If your tooling follows symlinks, it might see files from other targets (that were built beforehands) and happily use them, breaking bazel’s hermeticity. If you then run on another machine, where the other targets didn’t run before, the files will be missing and you get linker errors. Always try with a clean bazel workspace (`bazel clean`).

In your case you need to make sure that `libjava.so` is in the right place relative to `$(realpath libjvm.so)`.

**Comment by facundominguez** [comment]
> In your case you need to make sure that libjava.so is in the right place relative to $(realpath libjvm.so).

This is already the case, `$(realpath libjvm.so)` gives
```
/nix/store/2jf2amm76ig02m5myrn8bg852kxq65dv-openjdk-8u202bga/lib/openjdk/jre/lib/amd64/server/libjvm.so
```
and `libjava.so` is correctly located at
```
/nix/store/2jf2amm76ig02m5myrn8bg852kxq65dv-openjdk-8u202bga/lib/openjdk/jre/lib/amd64/libjava.so
```

I intend to copy or symlink libjvm.so and libjava.so to a fake file system hierarchy inside the runfiles directory, and see how that goes.

**Comment by mboes** [comment]
I'm a little surprised by this issue. Because if we give `"@bazel_tools//tools/jdk:current_java_runtime"` as a dependency and say something like:

```
print(ctx.files.deps)
```

then we get:

```
DEBUG: /home/mboes/.cache/bazel/_bazel_mboes/822aa44857e17f47d08bb198503f3032/external/io_tweag_rules_haskell/haskell/plugins.bzl:5:5: [
<source file external/local_jdk/bin/jaotc>, <source file external/local_jdk/bin/jar>,
<source file external/local_jdk/bin/jarsigner>, <source file external/local_jdk/bin/java>,
<source file external/local_jdk/bin/javac>,
[...]
<source file external/local_jdk/lib/libjava.so>,
[...]
```

Have you tried making your library depend on the entire JDK runtime? If you do that `libjava.so` will become visible at the right place I believe.

**Comment by facundominguez** [comment]
> Have you tried making your library depend on the entire JDK runtime?

I just tried it. Effectively, adds the JDK runtime to the runfiles, but it does no linking nor does it find the headers.

**Comment by Profpatsch** [comment]
Was this resolved in the meantime?

**Comment by facundominguez** [comment]
No, I haven't solved it yet, but I think we can close this issue as it belongs to inline-java now.
