### ISSUE TITLE
Custom haddock executable

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#848]
**Is your feature request related to a problem? Please describe.**

I want to change the `haddock` executable. For now I'm providing a `tool` argument to `haskell_toolchain` which point to a directory in which I manually overrode the `haddock` executable. This is not convenient.

**Describe the solution you'd like**

I want a way to explicitly set the `haddock` executable.

**Describe alternatives you've considered**

I see two alternatives:

- The current implementation looks for binaries (`haddock`, but also `ghc`, `hpc`, ...) in the label provided by the `tools` attribute of `haskell_toolchain`. I propose to change this attribute to a list of label. Binaries will be searched from this list in order.
- Implement an `haddock` toolchain similar to the `c2hs_toolchain` recently introduced by @m.

I'm in favor of the first solution that I consider simpler and more generic. @m what were the reasons for the introduction of `c2hs_toolchain`?

**Comment by Profpatsch** [comment]
How tightly is `haddock` bound to the rest of a GHC distribution? Does it depend on the specific version of libraries/binaries in the GHC distribution?

**Comment by mboes** [comment]
Yes pretty much. Which is why IMHO `haddock` should really be merged into the GHC repo. We have asked for that in the past (see https://mail.haskell.org/pipermail/ghc-devs/2019-March/017211.html), but to no avail.

There were two reasons for a separate `c2hs` toolchain:

* C2hs is a separate tool, which some people need and some people don't.
* C2hs is maintained separately from GHC and does not ship with GHC. Conflating it with GHC was weird.

Turning the `tools` attribute into a list of labels makes sense to me, even if I'm neutral about the merits of handling Haddock separately from GHC.

**Comment by guibou** [comment]
Ok. I'll submit my PR which turns `tools` to a list of label soon.
