### ISSUE TITLE
Allow a shorter name for haskell_register_ghc_nixpkgs internal repository

### ISSUE THREAD

**Issue by guibou** [tweag/rules_haskell#889]
**Is your feature request related to a problem? Please describe.**

`haskell_register_ghc_nixpkgs` generates an internal repository with a long name, `@io_tweag_rules_haskell_ghc_nixpkgs`, which clutter other bazel rules when you want to make reference to it, for exemple to load an haskell packages or to access some ghc binaries contained in this repository.

Could we have a way to setup a shorter name?

**Describe the solution you'd like**

```
haskell_register_ghc_nixpkgs(
   name = "shorter_name",
)
```

**Describe alternatives you've considered**

making `alias` for most of the item I'm interested in. That's a lot of boilerplate.

**Comment by mboes** [comment]
> Could we have a way to setup a shorter name?

Not really. The reason the name is that long is because it is a private name. In general, you should never refer to any name that you haven't textually written down yourself in a `WORKSPACE` file or `BUILD` file. e.g. if macros expand to multiple rules some of which were not named by you, then you should consider those private.

You shouldn't need to refer directly to the external repository containing GHC. The `WORKSPACE` file in rules_haskell has that currently, as a temporary hack for Hazel, but it's not going to play nice with cross compilation. Not forcing globally unique toolchains is precisely why Bazel has the `toolchain` mechanism. What's your use case?

**Comment by guibou** [comment]
> What's your use case?

I'm using some binaries and libraries provided by the toolchain and some associated packages. For example, my toolchain comes with the `hlint` haskell package which also provides `hlint` in the `bin` directory, I want to use that one.

**Comment by mboes** [comment]
Why are you sticking `hlint` into the compiler toolchain? If you customize the compiler toolchain, that should be to have it ship with extra libraries. I don't see any reason why binaries should be coupled to the toolchain as well.

**Comment by guibou** [comment]
> Why are you sticking hlint into the compiler toolchain?

For some packages I'm using the libraries and the binaries. The libraries comes with the compiler toolchain for simplicity (I'm using `ghcWithPackages`), and because the binaries comes too, I'd like to use them.

Of course I can write a separate `nixpkgs_package` for each packages for which I want binaries.

**Comment by mboes** [comment]
As argued elsewhere (I think in the context of `haskell_cabal_library`), binaries and libraries are very different beasts. There is no reason to pin binaries to a choice of snapshot constrained by library dependencies. The fact that Cabal puts both in the same package is kind of an accident of design. You should treat binaries as independent artifacts, i.e. use a separate `nixpkgs_package` for each. It's conceptually cleaner, and even better, you avoid wanting to depend on private details of `haskell_register_ghc_nixpkgs()`.

**Comment by mboes** [comment]
@guibou ok to close?

**Comment by guibou** [comment]
Ok.
