### ISSUE TITLE
Add upper bazel version warning

### ISSUE THREAD

**Issue by Profpatsch** [tweag/rules_haskell#923]
At any given time we only test against a given bazel version, while upstream releases new versions every month (currently we test `0.24` and upstream is at `0.26`).
Because of breaking changes in every bazel version, we cannot really support any version we don’t test (yet).

So we should add a warning to the `start` script (and the haskell toolchain?) if the bazel version is higher than what we checked before.

**Comment by aspiwack** [comment]
Indeed I hadn't found this one. Nevertheless, I'd like to add my propositions here (from #972 ). As I believe they should be addressed.

Let's face it: Bazel changes too fast to promise that a version of rules_haskell works even with two consecutive versions. So let's be prescriptive, and make it so that the start script _prescribes one precise version of Bazel_, and refuses to work otherwise (you may add a jailbreak button somewhere for the expert, but for the uninitiated, it's too much to deal with).

Because we are very much supporting Bazel being installed by nixpkgs, this means that the startup script should also give, in case of version mismatch, the user a version of nixpkgs where the proper Bazel is installed (it can be the same version pinned in the rules_haskell repository, this would make a lot of sense).

**Comment by ulysses4ever** [comment]
Is this the matter of adding two lines to the bash script? Or are there any deeper concerns preventing this to be closed?

**Comment by mboes** [comment]
> Is this the matter of adding two lines to the bash script?

Pretty much.

**Comment by ulysses4ever** [comment]
As a person bitten by too new Bazel (before switched to Nix), I went ahead and opened #974.

**Comment by ulysses4ever** [comment]
More optimistic strategy is in #975.

**Comment by Profpatsch** [comment]
Thank you @ulysses4ever!
