### ISSUE TITLE
symlink_dynamic_library takes an unreasonable amount of time

### ISSUE THREAD

**Issue by regnat** [tweag/rules_haskell#958]
**Describe the bug**

Building an haskell project from a clean action cache but a fully populated remote cache (or disk_cache) is painfully slow, most of the time being spent in `Symlink` actions due to `symlink_dynamic_library`.

For example, building `rules_haskell` with a pre-populated `disk_cache` and after a `bazel clean` takes ~70s while it takes ~10s if I comment https://github.com/tweag/rules_haskell/blob/1d2083299f5bbbf24408595f9b95a73a918bb662/haskell/providers.bzl#L269-L270

**To Reproduce**

On `rules_haskell`

```bash
# Ensure that we have a fully populated disk-cache
bazel build --disk_cache=/tmp/disk_cache //...
# Clean the action cache
bazel clean
# Rebuild the project
bazel build --disk_cache=/tmp/disk_cache //...
# Observe that it is unreasonably long for something which should just be pulling from a remote cache

# Repeat the above steps with haskell/providers.bzl#L269-L270 commented and admire how fast this is
```

**Expected behavior**

A fresh build with a remote cache should be fast

**Environment**
 - OS name + version: NixOS 19.09.git.b29d4de
 - Bazel version: 0.24.0 (provided from the nix-shell), also observed on 0.26.0
 - Version of the rules: 1d2083299f5bbbf24408595f9b95a73a918bb662 (current master)

**Comment by regnat** [comment]
(just to give some extra numbers, on the CI of a mid-sized haskell project I'm working on, commenting these two lines makes the build time drop from 4min to 50s)

**Comment by Profpatsch** [comment]
The solution here is probably to change the definition of `ln()` (which shells out to `ln(1)` for each call) to something that can symlink multiple files in the same action.

**Comment by guibou** [comment]
Are we sure that it is only `ln` which is problematic, or do we have any idea on the number of them?

```
λ paddle crevette → time bash -c "for i in \$(seq 10000); do ln -sf rules_nodejs-0.16.2 toto-\$i; done;"
bash -c   4.75s user 8.55s system 102% cpu 12.967 total
```

10K `ln` calls takes 12s. That's a lot, but @regnat is talking about 3minutes, which means roughly 150K symlinks, which feels too high.

**Comment by aherrmann** [comment]
@guibou With `ln()` in Bazel each symlink is created in its own action. Creating the sandbox for each these actions surely adds some overhead.

@Profpatsch batch `ln` is a nice idea. I've experimented with this in 53187de208573eccfa1f3c0ddfc9f5f5514a1687. Unfortunately, it doesn't quite work, it fails with "File generated by these conflicting actions". With the current implementation it's fine if `ln()` is called twice with the same arguments, because the action key will be identical Bazel takes care of deduplication. With the batch operation that's no longer the case. The whole batch of links that is being created has to be identical.

@regnat Those symlinks are being created to work around a number of limitations between GHC and Bazel.
- Bazel generates `.so` files on MacOS, which GHC doesn't understand. So we symlink to `.dylib`.
- Bazel generates `.a` and `.so` files with mismatching file names for `cc_library`, which GHC doesn't understand. So we symlink the `.a` to a matching name.
- The Haskell libraries created by `cc_common.create_library_to_link` each land in their individual directory under `bazel-bin/_solib_<cpu>` with very long paths. This quickly exceeds the MACH-O header size limit on MacOS. So we symlink all dynamic libraries into a common directory, so we only need one `RUNPATH` entry and the load commands are short. See https://github.com/bazelbuild/bazel/issues/8180.

The best solution is to fix those issues. 

I've been wondering if a different approach would be sufficient to work around all this. But I'm not sure if it works on MacOS in the required cases. Bazel just generates too long paths.
- For dynamic `haskell_library`
    - Don't mangle the input to `create_library_to_link`.
        E.g. create `libHSfoo.so` instead of `libHSsomeZSpackageZSfoo.so`. This name is not unique across packages, but Bazel avoids conflicts by creating an additional directory in `_solib_<cpu>`. This allows for a load command relative to `_solib_<cpu>` that would be shorter than a dedicated `RUNPATH` entry and load command with mangled name.
    - Create a symlink with mangled (unique) name for compile/link time.
        E.g. create a symlink with the mangled name `libHSsomeZSpackageZSfoo.so` for `libHSfoo.so`. This is so that we have a unique name across packages to put into GHC package configuration files.
    - Set `soname`/`install_name` to the path relative to `_solib_<cpu>`.
        E.g. `<mangled dir>/libHSfoo.so`. So that the linker automatically generates load commands relative to `_solib_<cpu>` and we only need one `RUNPATH` entry. Unfortunately, `<mangled dir>` tends to be about twice as long as the current mangled library names. So, this makes it more likely to exceed the MACH-O header size limit. See https://github.com/bazelbuild/bazel/issues/7415.
- For `cc_library` dependencies.
    - Patch load commands to load relative to `_solib_<cpu>`.
        E.g. `NEEDED libz.so.1  -->  NEEDED _U@zlib_S_S_Czlib___Uexternal_Szlib_Slib/libz.so.1`.
        (Hopefully it's sufficient to patch after linking. Otherwise we'd somehow have to patch the `soname`s/`install_name`s of the inputs.)

**Comment by mboes** [comment]
Isn't it possible to disable the sandbox on a per action basis?

**Comment by lunaris** [comment]
Are all these issues related to MacOS? If so, it is worth starting with a fix that uses `select` or the like to adapt based on the underlying platform?

**Comment by aherrmann** [comment]
@lunaris The dylib file ending and the MACH-O header size issues are MacOS specific. Though reducing the amount of `RUNPATH` entries should also be beneficial for Linux to speed up dynamic loading. The static archive name issue is independent of platform.
