### ISSUE TITLE
Document haskell toolchain registration macros

### ISSUE THREAD

**Issue by aspiwack** [tweag/rules_haskell#973]
The _use cases_ documentation (on master) uses

```python
nixpkgs_package(
    name = "ghc",
    repositories = { "nixpkgs": "@nixpkgs//:default.nix" },
    attribute_path = "haskell.compiler.ghc843", # Any compiler version
    build_file = "@io_tweag_rules_haskell//haskell:ghc.BUILD",
)

register_toolchains("//:ghc")
```
Together with a `haskell_toolchain` call in the `BUILD` file.

But I understand that, now, the recommended way uses `haskell_register_ghc_nixpkgs` instead of all that.

**Comment by mboes** [comment]
Recategorizing. BTW the documentation is up-to-date: the above mechanism still works as-is. However, it is incomplete, because there is now a new mechanism as well, and that one is better for most people.

**Comment by aspiwack** [comment]
In my experience it doesn't. Not out of the box anyway. Because the `haskell_toolchain` target now has (at least) one extra required field (`libraries`, I believe), and it's not obvious how to fill it (I failed). So advertising this method is probably not a good move.

**Comment by robinp** [comment]
I ran into the same problem - documentation on how to fill in `libraries` manually would be nice. The PR didn't address that.

**Comment by robinp** [comment]
I executed

```
cd my_ghc_derivation_result
python ~/srcs/rules_haskell/haskell/private/pkgdb_to_bzl.py ghc lib/ghc-8.6.3 > ../BUILD.part
```
then inserted the `BUILD.part` into my top `BUILD` file, and pointed `libraries = toolchain_libraries`, which was generated in the `BUILD.part`.

This made the libs available.

**Comment by mboes** [comment]
I'm not a fan of reopening long since closed PR's. @Profpatsch can you open a new one instead? `libraries` is the set of targets that describe libraries that ship with GHC. I have yet to see a use case where `haskell_register_ghc_*()` doesn't suffice. If you have a good use case for going lower level, do feel free to submit a documentation PR.

**Comment by robinp** [comment]
@mboes this is in context of https://github.com/tweag/rules_nixpkgs/issues/73, where I want to source GHC and libs from nix, build with bazel, and package the results using nix.

The problem is that when packaging with nix, the `rules_nixpkgs` rules can't execute (due to nix-in-nix), so setting up the haskell toolchain is not possible with the high-level macros.

Now I got a working config that runs the nix derivations (ghc and cc-toolchain) in advance, then uses the lower-level `haskell_toolchain`, `toolchain` and `register_toolchains` rules to get the same effect, but without directly triggering a nix-build.

**Comment by Profpatsch** [comment]
I’m not exactly sure how to translate that into a new issue, @robinp feel free to create one.

**Comment by mboes** [comment]
@robinp that's cunning. And in general we do need to have a good story for packaging in Nixpkgs. Could you create an issue about that more general problem? We'll want to pull in @edolstra to tell us about Nix-in-Nix, which AFAIK shouldn't be much work at this point to actually fix.

**Comment by robinp** [comment]
Opened https://github.com/tweag/rules_haskell/issues/1399.
