### ISSUE TITLE
haskell_cabal_library fails on packages with no modules

### ISSUE THREAD

**Issue by aspiwack** [tweag/rules_haskell#999]
I'm not entirely sure of my diagnosis, but I'm seeing an error when building the `bytestring-builder` package

```
ERROR: /home/aspiwack/.cache/bazel/_bazel_aspiwack/bd7cdf0b0195cd3d7f8d5aa71bc1df4e/external/stackage/BUILD.bazel:345:1: output 'external/stackage/bytestring-builder-0.10.8.2.0/_install/lib/libHSbytestring-builder-0.10.8.2.0.a' was not created
ERROR: /home/aspiwack/.cache/bazel/_bazel_aspiwack/bd7cdf0b0195cd3d7f8d5aa71bc1df4e/external/stackage/BUILD.bazel:345:1: output 'external/stackage/bytestring-builder-0.10.8.2.0/_install/lib/libHSbytestring-builder-0.10.8.2.0-ghc8.6.4.so' was not created
ERROR: /home/aspiwack/.cache/bazel/_bazel_aspiwack/bd7cdf0b0195cd3d7f8d5aa71bc1df4e/external/stackage/BUILD.bazel:345:1: not all outputs were created or valid
```

I ould check that `external/stackage/bytestring-builder-0.10.8.2.0/_install/lib/` exists but is empty.

My guess is the following: bytestring-builder is a compability package, on recent versions of ghc, it is an empty package. This seems to cause cabal to generate no file, but the rule for cabal package seems to promise a number of outputs, which are not created, and Bazel's action validation step fails.

I haven't made a reproducer yet. But it should be sufficient to generate a dummy Haskell project which depends on bytestring-builder.

**Environment**
 - OS name + version: Ubuntu 19.03
 - Bazel version: 0.27.0 (from a recent nixpkgs)
 - Version of the rules: f1cb56a4e05ebc3a5ce0560117ecddb2e0a3d673 (from a master today)

**Comment by aherrmann** [comment]
@aspiwack I think your guess exactly right. Hazel has [special handling for empty packages](https://github.com/tweag/rules_haskell/blob/8e7858057e9811767f0b7a310cb7a01377f6912b/hazel/third_party/cabal2bazel/bzl/cabal_package.bzl#L569), where it will generate a dummy `cc_library` target instead. Hazel can do this because it parses the Cabal file in a repository rule. Since `haskell_cabal_library` is a regular rule, it may be more difficult to find a workaround. Maybe we could extend the build script to check if no libraries were generated and generate empty libraries in that case.

**Comment by aspiwack** [comment]
That's a bit sad, because I don't have much control over this: I depend on a package which depends on a package which depends on bytestring-builder. Or something like this.

So I'm stuck until this is fixed or I find a workaround.

The only workaround that I can think of is to fork all the packages which depend directly on bytestring-builder to remove bytestring-builder from their .cabal. But that's pretty tedious. Any better idea?

**Comment by gdeest** [comment]
@aherrmann Bearing in mind that I don't know how all this is implemented: as a workaround, would it be possible to plain and shortly short-circuit `haskell_cabal_library` by having us pass an explicit list of empty packages to `stack_snapshot` ?

**Comment by aherrmann** [comment]
@gdeest That might work. You'd have to make sure to stitch up any holes this creates in the dependency graph. And you'd have to check that the package configuration file doesn't include anything important, e.g. C library references. Hopefully, that's the case for all such empty libraries.

Also, since this doesn't generate a target for those empty libraries, you cannot depend on them. That doesn't sound like a big issue, but worth mentioning.

Alternatively, you could generate empty libraries within the cabal build script if cabal didn't generate any. Something like
```
touch empty.c
gcc -c -o empty.o empty.c && ar rcs libempty.a empty.o
gcc -shared -o libempty.so empty.c
```
might work.

**Comment by mboes** [comment]
`nats` is another offender. It's worth noting that both `bytestring-builder` and `nats` could have used GHC's "reexported modules" feature, instead of the hack they both use. Presumably, they didn't do that because they are both aiming for compat going even further back than GHC 7.10 (this particular GHC feature only showed up then).
